'!include': 'shared/common.yaml'
outputDir: dotnet/generated
generatorName: csharp-netcore
library: httpclient # IDK why this one isn't working under additional properties
additionalProperties: # These seem to work at root or under `additionalProperties` idfk
  netCoreProjectFile: true
  nullableReferenceTypes: true
  optionalMethodArgument: true
  packageName: UnMango.Proxmox.Generated
  packageVersion: 0.1.0
  returnICollection: true
  sortParamsByRequiredFlag: true
  targetFramework: netstandard2.0;net5.0
  useDateTimeOffset: true
